### ISSUE TITLE
Revisión del README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto_dado_mentiroso_2021#1]
Hola,

He revisado el README:

- Faltan los objetivos.
- La propuesta es poco ambiciosa. La implementación de este único juego no exige demasiado esfuerzo, y no será necesario usar ficheros ni estructuras.

**Comment by SrGnar** [comment]
Ya hemos acabado de rellenar el README y hemos remodelado la propuesta como te ha comentado mi compañero @Christian7600 en la clase de hoy.
