### ISSUE TITLE
Entrega final del código

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto_dado_mentiroso_2021#7]
El código del trabajo debe estar completo, sin errores de compilación, y con las funcionalidades descritas en el README y en el diagrama de flujo.

Recordad que:

- Es obligatorio que el trabajo se realice con funciones.
- Es obligatorio utilizar vectores de estructuras.
- Es obligatorio utilizar ficheros.
- Está prohibido el uso de variables globales.

**Debéis cerrar esta issue cuando deis por finalizado el trabajo.**

**Comment by SrGnar** [comment]
Ya hemos revisado el código y terminado además de haber corregido todas las warnings. Si hubiera algún problema respecto a la instalación SDL no duden en comentárnoslo.
